import { firebaseConfig } from "./firebase-config.js";
import { SEED_DATA } from "./seed-data.js";

import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js";
import { getAuth, signInAnonymously, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js";
import {
  getFirestore, collection, doc, getDocs, setDoc, onSnapshot, query, orderBy,
  writeBatch, runTransaction, serverTimestamp, enableIndexedDbPersistence
} from "https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js";

const VERSION = "v1.0.0";
const STOCK_COLLECTION = "stockByBranch";
const STORAGE_KEY = "loveMatchaStockState_v1";
const UI_KEY = "loveMatchaStockUI_v1";
const REMEMBER_KEY = "loveMatchaStockRemember_v1";
const ROLE_LABEL = { owner: "เจ้าของ", manager: "ผู้จัดการ", employee: "พนักงาน" };
const TX_LABEL = {
  add_stock: "เติม stock", repack_add: "รีแพคชาเพิ่ม", repack_convert: "รีแพคแปลงขนาด", add_other: "เพิ่มอื่น ๆ",
  sale: "ขาย", front_fill: "เติมหน้าร้าน", transfer_out: "ส่งให้สาขาอื่น", stock_cut: "ตัด stock", reduce_other: "ลดอื่น ๆ",
  count: "นับใหม่", seed_import: "นำเข้าจาก Excel", transfer_in: "รับโอนเข้า", transfer_review: "โอนผิดปกติ"
};

let app = null, auth = null, db = null, renderTimer = null, autoBackupTimer = null;
let unsubscribers = [];
const state = {
  mode: "boot", online: navigator.onLine, firebaseReady: false, currentUser: null,
  users: [], branches: [], teas: [], sizes: [], stock: [], transactions: [], transferRequests: [], auditLogs: [], settings: {}, busy: false,
  ui: loadUiState()
};

document.addEventListener("DOMContentLoaded", boot);
window.addEventListener("online", () => { state.online = true; updateOnlineUI(); toast("กลับมาออนไลน์แล้ว", "ok"); render(); });
window.addEventListener("offline", () => { state.online = false; updateOnlineUI(); toast("ออฟไลน์อยู่ กรุณาต่ออินเตอร์เน็ตก่อน", "warn"); render(); });

async function boot() {
  registerServiceWorker();
  bindShellEvents();
  state.firebaseReady = isFirebaseConfigValid(firebaseConfig);
  if (state.firebaseReady) {
    try {
      app = initializeApp(firebaseConfig);
      auth = getAuth(app);
      db = getFirestore(app);
      try { await enableIndexedDbPersistence(db); } catch (err) { console.info("persistence skipped", err?.message || err); }
      await signInAnonymously(auth);
      onAuthStateChanged(auth, () => { state.mode = "firebase"; attachRealtimeListeners(); showLogin(); });
    } catch (err) {
      console.error(err); state.mode = "local"; loadLocalDemo(); showLogin();
      toast("ตั้งค่า Firebase ยังไม่สำเร็จ ระบบเปิดเป็นโหมดทดลองในเครื่อง", "warn");
    }
  } else {
    state.mode = "local"; loadLocalDemo(); showLogin();
  }
}
function isFirebaseConfigValid(cfg) { return !!(cfg && cfg.apiKey && cfg.projectId && !String(cfg.apiKey).includes("ใส่") && !String(cfg.projectId).includes("YOUR_")); }
function registerServiceWorker() { if ("serviceWorker" in navigator) navigator.serviceWorker.register("./service-worker.js").catch(console.info); }
function bindShellEvents() {
  document.getElementById("loginForm").addEventListener("submit", handleLogin);
  document.getElementById("logoutBtn").addEventListener("click", logout);
  document.getElementById("menuRefresh").addEventListener("click", () => location.reload());
  document.querySelectorAll(".nav-btn").forEach(btn => btn.addEventListener("click", () => setRoute(btn.dataset.route)));
}
function attachRealtimeListeners() {
  unsubscribers.forEach(fn => fn()); unsubscribers = [];
  const mapDocs = snap => snap.docs.map(d => ({ id: d.id, ...d.data() }));
  const listen = (col, cb, sortField = null) => {
    const ref = sortField ? query(collection(db, col), orderBy(sortField)) : collection(db, col);
    const unsub = onSnapshot(ref, snap => { cb(mapDocs(snap)); scheduleRender(); }, err => toast(`โหลด ${col} ไม่สำเร็จ: ${err.message}`, "error"));
    unsubscribers.push(unsub);
  };
  listen("users", docs => state.users = docs, "displayName");
  listen("branches", docs => state.branches = docs, "order");
  listen("teas", docs => state.teas = docs, "order");
  listen("sizes", docs => state.sizes = docs, "order");
  listen(STOCK_COLLECTION, docs => state.stock = docs);
  listen("transactions", docs => state.transactions = docs.sort((a,b) => String(b.savedAt || "").localeCompare(String(a.savedAt || ""))));
  listen("transferRequests", docs => state.transferRequests = docs.sort((a,b) => String(b.createdAt || "").localeCompare(String(a.createdAt || ""))));
  listen("auditLogs", docs => state.auditLogs = docs.sort((a,b) => String(b.createdAt || "").localeCompare(String(a.createdAt || ""))).slice(0, 250));
  unsubscribers.push(onSnapshot(doc(db, "settings", "global"), snap => { state.settings = snap.exists() ? { id: snap.id, ...snap.data() } : defaultSettings(); applySettings(); scheduleRender(); }));
}
function defaultSettings(now = new Date().toISOString()) {
  return { id: "global", appName: "Love Matcha Stock", version: VERSION, themeColor: "#356B23", fontScale: 1, logoDataUrl: "", managerCanExport: true, googleScriptUrl: "", autoBackup: "off", lastBackupAt: "", lastBackupStatus: "", createdAt: now, updatedAt: now };
}
function seedToState() {
  const now = new Date().toISOString();
  const owner = { id: "user_owner", displayName: "เจ้าของ", role: "owner", pin: "1234", branchIds: SEED_DATA.branches.map(b => b.id), active: true, requirePinChange: true, createdAt: now, updatedAt: now };
  const stock = SEED_DATA.stock.map(s => ({ id: stockDocId(s.branchId, s.teaId, s.sizeId), branchId: s.branchId, teaId: s.teaId, sizeId: s.sizeId, qty: Number(s.qty || 0), threshold: 0, updatedAt: now }));
  const transactions = SEED_DATA.branches.map(branch => ({ id: `tx_seed_${branch.id}`, transactionId: `tx_seed_${branch.id}`, type: "seed_import", typeLabel: "นำเข้าจาก Excel", status: "completed", branchId: branch.id, branchName: branch.name, actionDate: todayISO(), savedAt: now, userId: "system", userName: "ระบบ", userRole: "system", note: `นำเข้า Stock ปัจจุบันจาก ${SEED_DATA.sourceWorkbook}`, hidden: false, items: stock.filter(s => s.branchId === branch.id && Number(s.qty) !== 0), createdAt: now, updatedAt: now }));
  return { users: [owner], branches: SEED_DATA.branches, teas: SEED_DATA.teas, sizes: SEED_DATA.sizes, stock, transactions, transferRequests: [], auditLogs: [], settings: defaultSettings(now) };
}
function loadLocalDemo() {
  const saved = localStorage.getItem(STORAGE_KEY);
  if (saved) { try { Object.assign(state, JSON.parse(saved), { mode: "local", online: navigator.onLine, firebaseReady: false, currentUser: null }); applySettings(); return; } catch {} }
  Object.assign(state, seedToState(), { mode: "local", online: navigator.onLine, firebaseReady: false }); persistLocal();
}
function persistLocal() {
  if (state.mode !== "local") return;
  const data = { users: state.users, branches: state.branches, teas: state.teas, sizes: state.sizes, stock: state.stock, transactions: state.transactions, transferRequests: state.transferRequests, auditLogs: state.auditLogs, settings: state.settings };
  localStorage.setItem(STORAGE_KEY, JSON.stringify(data));
}
function loadUiState() { try { return { route: "dashboard", selectedBranchId: "", stockSearch: "", sizeFilter: "", historyRange: "7d", historyBranch: "all", actionTab: "add", ...JSON.parse(localStorage.getItem(UI_KEY) || "{}") }; } catch { return { route: "dashboard", selectedBranchId: "", stockSearch: "", sizeFilter: "", historyRange: "7d", historyBranch: "all", actionTab: "add" }; } }
function saveUiState() { localStorage.setItem(UI_KEY, JSON.stringify(state.ui)); }
function showLogin() { document.getElementById("boot").classList.add("hidden"); document.getElementById("appShell").classList.add("hidden"); document.getElementById("loginView").classList.remove("hidden"); renderLogin(); }
function showApp() { document.getElementById("boot").classList.add("hidden"); document.getElementById("loginView").classList.add("hidden"); document.getElementById("appShell").classList.remove("hidden"); if (!state.ui.selectedBranchId) state.ui.selectedBranchId = primaryBranchId(); setRoute(state.ui.route || "dashboard", false); startAutoBackup(); render(); }
function renderLogin() {
  const users = activeUsers(); const select = document.getElementById("loginUser"); const remembered = JSON.parse(localStorage.getItem(REMEMBER_KEY) || "{}");
  select.innerHTML = users.map(u => `<option value="${h(u.id)}">${h(u.displayName)} · ${h(roleLabel(u.role))}</option>`).join("");
  if (remembered.userId && users.some(u => u.id === remembered.userId)) select.value = remembered.userId;
  document.getElementById("loginPin").value = remembered.pin || "";
  document.getElementById("rememberUser").checked = !!remembered.userId; document.getElementById("rememberPin").checked = !!remembered.pin;
  const setup = document.getElementById("setupBox");
  if (state.mode === "firebase" && users.length === 0) {
    setup.classList.remove("hidden"); setup.innerHTML = `<b>ยังไม่มีข้อมูลเริ่มต้นใน Firebase</b><p class="muted">กดเพื่อติดตั้ง owner, สาขา, รายการชา, ขนาด และ stock จาก Excel</p><button class="primary full" id="seedBtn">ติดตั้งข้อมูลเริ่มต้น v1.0.0</button>`;
    setTimeout(() => document.getElementById("seedBtn")?.addEventListener("click", seedFirestore), 0);
  } else if (state.mode === "local") { setup.classList.remove("hidden"); setup.innerHTML = `<b>โหมดทดลองในเครื่อง</b><p class="muted">ยังไม่ได้ใส่ Firebase config จึงไม่ realtime ข้ามเครื่อง</p>`; }
  else setup.classList.add("hidden");
}
async function handleLogin(evt) {
  evt.preventDefault(); const userId = val("loginUser"); const pin = onlyDigits(val("loginPin")).slice(0, 4); const user = state.users.find(u => u.id === userId && u.active !== false);
  if (!user) return toast("ไม่พบ user หรือ user ถูกปิดใช้งาน", "error");
  if (!/^\d{4}$/.test(pin)) return toast("PIN ต้องเป็นตัวเลข 4 ตัว", "error");
  if (String(user.pin) !== pin) return toast("PIN ไม่ถูกต้อง", "error");
  state.currentUser = user;
  const remember = {}; if (document.getElementById("rememberUser").checked) remember.userId = userId; if (document.getElementById("rememberPin").checked) remember.pin = pin; localStorage.setItem(REMEMBER_KEY, JSON.stringify(remember));
  await audit("login", "เข้าสู่ระบบ"); if (user.requirePinChange) { toast("แนะนำให้เปลี่ยน PIN เริ่มต้น 1234 ทันที", "warn"); state.ui.route = "settings"; }
  showApp();
}
function logout() { state.currentUser = null; stopAutoBackup(); showLogin(); }
function setRoute(route, doRender = true) { state.ui.route = route; saveUiState(); document.querySelectorAll(".nav-btn").forEach(btn => btn.classList.toggle("active", btn.dataset.route === route)); if (doRender) render(); }
function scheduleRender() { clearTimeout(renderTimer); renderTimer = setTimeout(render, 80); }
function updateOnlineUI() { const badge = document.getElementById("onlineBadge"); if (!badge) return; badge.textContent = state.online ? "ออนไลน์" : "ออฟไลน์"; badge.classList.toggle("offline", !state.online); }
function applySettings() { const s = state.settings || defaultSettings(); document.documentElement.style.setProperty("--matcha", s.themeColor || "#356B23"); document.documentElement.style.setProperty("--font-scale", String(s.fontScale || 1)); }
function render() {
  if (!state.currentUser) { renderLogin(); return; }
  applySettings(); updateOnlineUI();
  const b = branchById(state.ui.selectedBranchId || primaryBranchId());
  document.getElementById("currentContext").textContent = `${roleLabel(state.currentUser.role)} · ${b ? b.name : "รวมทุกสาขา"} · ${VERSION}`;
  const logo = state.settings.logoDataUrl || "./assets/logo.jpg"; document.getElementById("appLogo").src = logo; document.getElementById("loginLogo").src = logo;
  const main = document.getElementById("main"); const route = state.ui.route || "dashboard";
  if (route === "dashboard") main.innerHTML = renderDashboard();
  if (route === "stock") main.innerHTML = renderStockPage();
  if (route === "action") main.innerHTML = renderActionPage();
  if (route === "transfers") main.innerHTML = renderTransfersPage();
  if (route === "history") main.innerHTML = renderHistoryPage();
  if (route === "settings") main.innerHTML = renderSettingsPage();
  bindPageEvents(route);
}
function titleBlock(title, subtitle = "", extra = "") { return `<div class="page-title"><div><h2>${h(title)}</h2>${subtitle ? `<p>${h(subtitle)}</p>` : ""}</div>${extra}</div>`; }
function offlineWarning() { return state.online ? "" : `<div class="error-box mb">ออฟไลน์อยู่ กรุณาต่ออินเตอร์เน็ตก่อน — เปิดดูข้อมูลล่าสุดได้ แต่ปิดการบันทึกเพื่อป้องกันข้อมูลชนกัน</div>`; }
function renderDashboard() {
  const myBranch = primaryBranchId(); const low = lowStockItems(); const neg = state.stock.filter(s => Number(s.qty) < 0); const pending = pendingTransfersForCurrentUser();
  const allCount = state.stock.reduce((sum, s) => sum + Number(s.qty || 0), 0); const myCount = state.stock.filter(s => s.branchId === myBranch).reduce((sum, s) => sum + Number(s.qty || 0), 0);
  const totals = aggregateTotalStock();
  return `${titleBlock("หน้าแรก", "ภาพรวม stock รวมทุกสาขาและสาขาของฉัน", `<span class="chip">${VERSION}</span>`)}${offlineWarning()}
  <div class="grid two"><div class="card kpi"><div class="value">${fmt(allCount)}</div><div class="label">จำนวนถุงรวมทุกสาขา</div></div><div class="card kpi"><div class="value">${fmt(myCount)}</div><div class="label">จำนวนถุงสาขาของฉัน</div></div><div class="card kpi"><div class="value">${fmt(low.length)}</div><div class="label">รายการใกล้หมด</div></div><div class="card kpi"><div class="value">${fmt(pending.length)}</div><div class="label">โอนรอยืนยัน</div></div></div>
  <div class="card mt"><h3>ทำรายการเร็ว</h3><div class="action-row"><button class="primary" data-action-route="add">เพิ่มชา</button><button class="secondary" data-action-route="reduce">ลดชา</button><button class="secondary" data-action-route="count">นับใหม่</button><button class="secondary" data-action-route="transfer">ส่งให้สาขาอื่น</button></div></div>
  <div class="grid auto mt"><div class="card"><h3>Stock รวมทุกสาขา</h3>${totals.slice(0,8).map(i => `<div class="audit-line"><b>${h(i.teaName)} ${h(i.sizeLabel)}</b><small>${fmt(i.qty)} ถุง</small></div>`).join("") || `<p class="muted">ยังไม่มีข้อมูล stock</p>`}<button class="ghost full mt" data-go-stock="total">ดู Stock รวมทั้งหมด</button></div>
  <div class="card"><h3>รายการโอนรอยืนยัน</h3>${pending.slice(0,5).map(transferMiniCard).join("") || `<p class="muted">ไม่มีรายการรอยืนยัน</p>`}<button class="ghost full mt" data-route-to="transfers">เปิดหน้าโอนรอยืนยัน</button></div>
  <div class="card"><h3>รายการใกล้หมด</h3>${low.slice(0,8).map(s => `<div class="audit-line"><b>${h(getTeaName(s.teaId))} ${h(getSizeLabel(s.sizeId))}</b><small>${h(getBranchName(s.branchId))} · เหลือ ${fmt(s.qty)} / เตือน ≤ ${fmt(s.threshold)}</small></div>`).join("") || `<p class="muted">ยังไม่มีรายการใกล้หมด หรือ threshold เป็น 0</p>`}</div>
  <div class="card"><h3>ผิดปกติ / ติดลบ</h3>${neg.slice(0,8).map(s => `<div class="audit-line"><b>${h(getTeaName(s.teaId))} ${h(getSizeLabel(s.sizeId))}</b><small>${h(getBranchName(s.branchId))} · ${fmt(s.qty)} ถุง</small></div>`).join("") || `<p class="muted">ไม่พบยอดติดลบ</p>`}</div></div>`;
}
function renderStockPage() {
  const branchId = state.ui.selectedBranchId || primaryBranchId(); const isTotal = branchId === "all"; const list = getStockList(branchId); const search = state.ui.stockSearch || ""; const sizeFilter = state.ui.sizeFilter || "";
  const filtered = list.filter(item => (!search || item.teaName.toLowerCase().includes(search.toLowerCase())) && (!sizeFilter || item.sizeId === sizeFilter)); const grouped = groupBy(filtered, "teaId");
  return `${titleBlock("สต๊อก", isTotal ? "Stock รวมทุกสาขาแบบ realtime" : `Stock สาขา ${getBranchName(branchId)}`)}${offlineWarning()}${branchTabs(branchId, true)}
  <div class="card mb"><div class="form-grid"><label>ค้นหาชื่อชา<input id="stockSearch" value="${h(search)}" placeholder="เช่น Yame, Uji, Roast"></label><label>กรองขนาด<select id="stockSizeFilter"><option value="">ทุกขนาด</option>${activeSizes().map(s => `<option value="${h(s.id)}" ${s.id===sizeFilter?"selected":""}>${h(s.label)}</option>`).join("")}</select></label></div></div>
  <div class="grid auto">${Object.entries(grouped).map(([teaId, items]) => stockTeaCard(teaId, items, isTotal)).join("") || `<div class="card"><p class="muted">ไม่พบรายการที่ค้นหา</p></div>`}</div>`;
}
function stockTeaCard(teaId, items, isTotal) {
  const tea = teaById(teaId); const total = items.reduce((sum,i)=>sum+Number(i.qty||0),0); const low = items.some(i => Number(i.threshold||0)>0 && Number(i.qty)<=Number(i.threshold)); const neg = items.some(i=>Number(i.qty)<0);
  return `<div class="card stock-card"><div class="stock-head"><div><b>${h(tea?.displayName || teaId)}</b><div class="muted small">${fmt(total)} ถุงรวม${isTotal ? "ทุกสาขา" : ""}</div></div><div>${neg?`<span class="badge neg">ติดลบ</span>`:low?`<span class="badge low">ใกล้หมด</span>`:`<span class="badge">ปกติ</span>`}</div></div><div class="size-grid">${items.sort(sortBySize).map(item => `<div class="size-pill"><small>${h(item.sizeLabel)}</small><div class="qty">${fmt(item.qty)}</div>${item.threshold>0?`<small>เตือน ≤ ${fmt(item.threshold)}</small>`:`<small>ไม่ตั้งเตือน</small>`}</div>`).join("")}</div></div>`;
}
function branchTabs(currentId, includeAll = false) { const branches = sortedBranchesForUser(); return `<div class="branch-tabs">${includeAll ? `<button class="tab ${currentId === "all" ? "active" : ""}" data-branch-tab="all">รวมทุกสาขา</button>` : ""}${branches.map(b => `<button class="tab ${currentId === b.id ? "active" : ""} ${isMyBranch(b.id) ? "mine" : ""}" data-branch-tab="${h(b.id)}">${isMyBranch(b.id) ? "⭐ " : ""}${h(b.name)}</button>`).join("")}</div>`; }
function renderActionPage() { const tab = state.ui.actionTab || "add"; return `${titleBlock("เพิ่ม-ลด stock", "เลือกประเภทให้ตรงกับงานจริงเพื่อให้ประวัติถูกต้อง")}${offlineWarning()}<div class="tabs">${[["add","เพิ่มชา"],["reduce","ลดชา"],["count","นับใหม่"],["transfer","ส่งสาขา"],["repack","รีแพค"]].map(([id,l]) => `<button class="tab ${tab===id?"active":""}" data-action-tab="${id}">${l}</button>`).join("")}</div><div class="card">${tab==="add"?addForm():tab==="reduce"?reduceForm():tab==="count"?countForm():tab==="transfer"?transferForm():repackForm()}</div>`; }
function commonFields(prefix) { const branchId = state.ui.selectedBranchId || primaryBranchId(); const firstTea = activeTeas()[0]?.id || ""; const sizes = activeSizes().filter(s => (teaById(firstTea)?.sizeIds || []).includes(s.id)); return `<div class="form-grid"><label>วันที่ทำรายการ<input id="${prefix}Date" type="date" value="${todayISO()}"></label><label>สาขา<select id="${prefix}Branch">${sortedBranchesForUser().map(b=>`<option value="${h(b.id)}" ${b.id===branchId?"selected":""}>${h(b.name)}${isMyBranch(b.id)?" ⭐":""}</option>`).join("")}</select></label><label>ชื่อชา<select id="${prefix}Tea" data-size-target="${prefix}Size">${activeTeas().map(t=>`<option value="${h(t.id)}">${h(t.displayName)}</option>`).join("")}</select></label><label>ขนาด<select id="${prefix}Size">${sizes.map(s=>`<option value="${h(s.id)}">${h(s.label)}</option>`).join("")}</select></label></div>`; }
function qtyControl(id, label = "จำนวน") { return `<label>${h(label)}<div class="qty-control"><input id="${id}" type="number" inputmode="numeric" min="0" step="1" value="1"><div class="quick-buttons" data-qty-for="${id}"><button type="button" data-delta="-1">-1</button><button type="button" data-delta="1">+1</button><button type="button" data-delta="5">+5</button><button type="button" data-delta="10">+10</button></div></div></label>`; }
function addForm() { return `<form id="addForm" class="form-section"><h3>เพิ่มชา</h3><label>ประเภทเพิ่มชา<select id="addType"><option value="add_stock">เติม stock</option><option value="repack_add">รีแพคชาเพิ่ม</option><option value="add_other">อื่น ๆ ให้ระบุ</option></select></label>${commonFields("add")}${qtyControl("addQty")}<label>หมายเหตุ<textarea id="addNote" placeholder="เช่น รับของจาก supplier, เลข lot"></textarea></label><button class="primary full" ${writeDisabledAttr()}>บันทึกเพิ่มชา</button></form>`; }
function reduceForm() { return `<form id="reduceForm" class="form-section"><h3>ลดชา</h3><label>ประเภทลดชา<select id="reduceType"><option value="sale">ขาย</option><option value="front_fill">เติมหน้าร้าน</option><option value="stock_cut">ตัด stock</option><option value="reduce_other">อื่น ๆ ให้ระบุ</option></select></label>${commonFields("reduce")}${qtyControl("reduceQty")}<label>หมายเหตุ<textarea id="reduceNote" placeholder="เช่น เติมหน้าร้าน/ตัดเสียหาย"></textarea></label><button class="primary full" ${writeDisabledAttr()}>บันทึกลดชา</button></form>`; }
function countForm() { return `<form id="countForm" class="form-section"><h3>นับใหม่ / Adjustment</h3>${commonFields("count")}${qtyControl("countQty", "จำนวนจริงที่นับได้")}<label>หมายเหตุ<textarea id="countNote" placeholder="บังคับใส่ถ้าจำนวนลดลงมาก"></textarea></label><div class="warning-box">ระบบบันทึกก่อนนับ/หลังนับ/ส่วนต่างไว้ตรวจสอบย้อนหลัง</div><button class="primary full" ${writeDisabledAttr()}>บันทึกนับใหม่</button></form>`; }
function transferForm() { return `<form id="transferForm" class="form-section"><h3>ส่งชาให้สาขาอื่น</h3><div class="form-grid"><label>วันที่ทำรายการ<input id="transferDate" type="date" value="${todayISO()}"></label><label>สาขาต้นทาง<select id="transferFrom">${sortedBranchesForUser().map(b=>`<option value="${h(b.id)}" ${b.id===primaryBranchId()?"selected":""}>${h(b.name)}${isMyBranch(b.id)?" ⭐":""}</option>`).join("")}</select></label><label>สาขาปลายทาง<select id="transferTo">${activeBranches().map(b=>`<option value="${h(b.id)}">${h(b.name)}</option>`).join("")}</select></label><label>ชื่อชา<select id="transferTea" data-size-target="transferSize">${activeTeas().map(t=>`<option value="${h(t.id)}">${h(t.displayName)}</option>`).join("")}</select></label><label>ขนาด<select id="transferSize">${activeSizes().map(s=>`<option value="${h(s.id)}">${h(s.label)}</option>`).join("")}</select></label></div>${qtyControl("transferQty")}<label>หมายเหตุ<textarea id="transferNote"></textarea></label><div class="warning-box">กดยืนยันแล้ว stock ต้นทางลดทันที ปลายทางต้องรับก่อน stock เพิ่ม</div><button class="primary full" ${writeDisabledAttr()}>ยืนยันส่งของ</button></form>`; }
function repackForm() { const mode = state.ui.repackMode || "simple"; return `<div class="form-section"><h3>รีแพคชา</h3><div class="tabs"><button class="tab ${mode==="simple"?"active":""}" data-repack-mode="simple">เพิ่มแบบง่าย</button><button class="tab ${mode==="convert"?"active":""}" data-repack-mode="convert">แปลงขนาด</button></div>${mode==="simple"?`<form id="repackSimpleForm" class="form-section">${commonFields("repackSimple")}${qtyControl("repackSimpleQty", "จำนวนที่รีแพคเพิ่ม")}<label>หมายเหตุ<textarea id="repackSimpleNote"></textarea></label><button class="primary full" ${writeDisabledAttr()}>บันทึกรีแพคเพิ่ม</button></form>`:`<form id="repackConvertForm" class="form-section"><div class="form-grid"><label>วันที่ทำรายการ<input id="repackConvertDate" type="date" value="${todayISO()}"></label><label>สาขา<select id="repackConvertBranch">${sortedBranchesForUser().map(b=>`<option value="${h(b.id)}">${h(b.name)}${isMyBranch(b.id)?" ⭐":""}</option>`).join("")}</select></label><label>ชื่อชา<select id="repackConvertTea">${activeTeas().map(t=>`<option value="${h(t.id)}">${h(t.displayName)}</option>`).join("")}</select></label><label>ลดจากขนาด<select id="repackFromSize">${activeSizes().map(s=>`<option value="${h(s.id)}" ${s.grams===1000?"selected":""}>${h(s.label)}</option>`).join("")}</select></label><label>จำนวนต้นทาง<input id="repackFromQty" type="number" inputmode="numeric" min="1" value="1"></label><label>เพิ่มเป็นขนาด<select id="repackToSize">${activeSizes().map(s=>`<option value="${h(s.id)}" ${s.grams===40?"selected":""}>${h(s.label)}</option>`).join("")}</select></label><label>จำนวนปลายทาง<input id="repackToQty" type="number" inputmode="numeric" min="1" value="25"></label></div><label>หมายเหตุ<textarea id="repackConvertNote" placeholder="เช่น 1000gm 1 ถุง เป็น 40gm 25 ถุง"></textarea></label><div id="repackGramCheck" class="warning-box"></div><button class="primary full" ${writeDisabledAttr()}>บันทึกแปลงขนาด</button></form>`}</div>`; }
function renderTransfersPage() { const pending = state.transferRequests.filter(t=>t.status==="pending"); const review = state.transferRequests.filter(t=>t.status==="review_required" || t.status==="rejected"); const done = state.transferRequests.filter(t=>t.status==="completed").slice(0,30); return `${titleBlock("โอนรอยืนยัน", "ปลายทางต้องกดยืนยันก่อน stock จะเพิ่ม")}${offlineWarning()}<div class="grid auto"><div class="card"><h3>รอยืนยัน (${pending.length})</h3>${pending.map(transferCard).join("") || `<p class="muted">ไม่มีรายการรอยืนยัน</p>`}</div><div class="card"><h3>ผิดปกติ / ต้องตรวจสอบ (${review.length})</h3>${review.map(transferCard).join("") || `<p class="muted">ไม่มีรายการผิดปกติ</p>`}</div><div class="card"><h3>ยืนยันแล้วล่าสุด</h3>${done.map(transferMiniCard).join("") || `<p class="muted">ยังไม่มีรายการยืนยันแล้ว</p>`}</div></div>`; }
function transferMiniCard(t) { return `<div class="audit-line"><b>${h(getTeaName(t.teaId))} ${h(getSizeLabel(t.sizeId))} · ${fmt(t.qty)} ถุง</b><small>${h(getBranchName(t.fromBranchId))} → ${h(getBranchName(t.toBranchId))} · ${statusBadge(t.status)}</small></div>`; }
function transferCard(t) { const can = canConfirmTransfer(t); return `<div class="audit-line"><div class="row"><b>${h(getTeaName(t.teaId))} ${h(getSizeLabel(t.sizeId))}</b>${statusBadge(t.status)}</div><small>${h(getBranchName(t.fromBranchId))} → ${h(getBranchName(t.toBranchId))} · ส่ง ${fmt(t.qty)} · ${formatDateTime(t.createdAt)}</small>${t.note?`<small>หมายเหตุ: ${h(t.note)}</small>`:""}${t.status==="pending" && can ? `<div class="action-row mt"><button class="primary small" data-confirm-transfer="${h(t.id)}">รับครบ ถูกต้อง</button><button class="warn small" data-reject-transfer="${h(t.id)}">ไม่ตรง/ปฏิเสธ</button></div>`:""}${t.status!=="pending"?`<small>ผลรับ: ${fmt(t.receivedQty ?? t.qty)} · ${h(t.receiveNote || "")}</small>`:""}</div>`; }
function statusBadge(status) { const map = { pending:["รอยืนยัน","pending"], completed:["เสร็จแล้ว",""], rejected:["ปฏิเสธ","neg"], review_required:["ต้องตรวจสอบ","low"], cancelled:["ยกเลิก","hidden"] }; const [label, cls] = map[status] || [status,""]; return `<span class="badge ${cls}">${h(label)}</span>`; }
function renderHistoryPage() { const txs = filteredTransactions(); return `${titleBlock("ประวัติ", "กรองตามวัน สาขา user ประเภท ชื่อชา และรายการผิดปกติ")}<div class="card mb"><div class="form-grid"><label>ช่วงวันที่<select id="historyRange">${[["today","วันนี้"],["7d","7 วันล่าสุด"],["month","เดือนนี้"],["custom","เลือกเอง"]].map(([v,l])=>`<option value="${v}" ${state.ui.historyRange===v?"selected":""}>${l}</option>`).join("")}</select></label><label>สาขา<select id="historyBranch"><option value="all">รวมทุกสาขา</option>${activeBranches().map(b=>`<option value="${h(b.id)}" ${state.ui.historyBranch===b.id?"selected":""}>${h(b.name)}</option>`).join("")}</select></label><label>ประเภท<select id="historyType"><option value="">ทุกประเภท</option>${Object.entries(TX_LABEL).map(([v,l])=>`<option value="${v}" ${state.ui.historyType===v?"selected":""}>${h(l)}</option>`).join("")}</select></label><label>ค้นหา user/ชา/หมายเหตุ<input id="historySearch" value="${h(state.ui.historySearch || "")}" placeholder="พิมพ์คำค้นหา"></label></div><div id="customRange" class="form-grid mt ${state.ui.historyRange==="custom"?"":"hidden"}"><label>จากวันที่ <input id="historyFrom" type="date" value="${h(state.ui.historyFrom || todayISO())}"></label><label>ถึงวันที่ <input id="historyTo" type="date" value="${h(state.ui.historyTo || todayISO())}"></label></div></div><div class="card"><h3>รายการประวัติ (${txs.length})</h3><div class="table-wrap"><table><thead><tr><th>วันที่ทำรายการ</th><th>เวลาบันทึก</th><th>สาขา</th><th>ประเภท</th><th>รายการ</th><th>ก่อน/หลัง</th><th>ผู้ทำ</th><th>หมายเหตุ</th><th>สถานะ</th></tr></thead><tbody>${txs.map(historyRow).join("") || `<tr><td colspan="9" class="muted">ไม่พบประวัติ</td></tr>`}</tbody></table></div></div>`; }
function historyRow(tx) { const hidden = !!tx.hidden; const items = tx.items?.length ? tx.items.map(i=>`${h(getTeaName(i.teaId))} ${h(getSizeLabel(i.sizeId))} ${fmt(i.beforeQty)}→${fmt(i.afterQty)}`).join("<br>") : `${h(tx.teaName || getTeaName(tx.teaId))} ${h(tx.sizeLabel || getSizeLabel(tx.sizeId))}`; return `<tr class="${hidden?"hidden-row":""}"><td>${formatDate(tx.actionDate)}</td><td>${formatDateTime(tx.savedAt)}</td><td>${h(getBranchName(tx.branchId || tx.fromBranchId || tx.toBranchId))}</td><td>${h(tx.typeLabel || TX_LABEL[tx.type] || tx.type || "-")}</td><td>${items}</td><td>${tx.items?.length?"":`${fmt(tx.beforeQty)} → ${fmt(tx.afterQty)}`}</td><td>${h(tx.userName || "-")}<br><small>${h(roleLabel(tx.userRole || ""))}</small></td><td>${h(tx.note || "")}<br><small>${h(tx.device || "")}</small></td><td>${statusBadge(tx.status || "completed")}${hidden?`<span class="badge hidden">ซ่อน</span>`:""}${isOwner()?`<br><button class="ghost small mt" data-toggle-hidden="${h(tx.id)}">${hidden?"แสดงกลับ":"ซ่อนประวัติ"}</button>`:""}</td></tr>`; }
function renderSettingsPage() { return `${titleBlock("ตั้งค่า", "แสดงเฉพาะเมนูตามสิทธิ์ของผู้ใช้")}<div class="grid auto">${profileSettings()}${canManageUsers()?userManagement():""}${isOwner()?branchManagement():""}${canManageTea()?teaManagement():""}${isOwner()?sizeManagement():""}${canManageThresholds()?thresholdSettings():""}${isOwner()?appearanceSettings():""}${canExportBackup()?backupSettings():""}${isOwner()?auditSettings():""}</div>`; }
function profileSettings() { return `<div class="card"><h3>ข้อมูลของฉัน</h3><p><b>${h(state.currentUser.displayName)}</b> · ${h(roleLabel(state.currentUser.role))}</p><form id="pinForm" class="stack"><label>PIN เดิม <input id="oldPin" type="password" inputmode="numeric" maxlength="4"></label><label>PIN ใหม่ 4 ตัว <input id="newPin" type="password" inputmode="numeric" maxlength="4"></label><button class="primary" ${writeDisabledAttr()}>เปลี่ยน PIN</button></form></div>`; }
function userManagement() { return `<div class="card"><h3>จัดการ user</h3><form id="addUserForm" class="stack"><label>ชื่อ user <input id="newUserName" placeholder="เช่น พนักงานหนองคาย"></label><label>บทบาท<select id="newUserRole">${isOwner()?`<option value="owner">เจ้าของ</option><option value="manager">ผู้จัดการ</option>`:""}<option value="employee">พนักงาน</option></select></label><label>สาขาหลัก<select id="newUserBranch">${activeBranches().map(b=>`<option value="${h(b.id)}">${h(b.name)}</option>`).join("")}</select></label><label>PIN เริ่มต้น <input id="newUserPin" inputmode="numeric" maxlength="4" value="1234"></label><button class="primary" ${writeDisabledAttr()}>เพิ่ม user</button></form><h3 class="mt">รายชื่อ</h3>${activeUsers().map(u=>`<div class="audit-line"><b>${h(u.displayName)} · ${h(roleLabel(u.role))}</b><small>สาขา: ${(u.branchIds||[]).map(getBranchName).join(", ") || "-"}</small>${isOwner()?`<small>PIN: <b>${h(u.pin || "")}</b></small>`:""}<div class="action-row"><button class="ghost small" data-edit-user="${h(u.id)}">แก้ไข/reset</button>${u.id!==state.currentUser.id?`<button class="danger small" data-disable-user="${h(u.id)}">ปิดใช้</button>`:""}</div></div>`).join("")}</div>`; }
function branchManagement() { return `<div class="card"><h3>จัดการสาขา</h3><form id="addBranchForm" class="stack"><label>ชื่อสาขาใหม่ <input id="branchName" placeholder="เช่น ขอนแก่น"></label><button class="primary" ${writeDisabledAttr()}>เพิ่มสาขา</button></form><div class="mt">${state.branches.map(b=>`<div class="audit-line"><b>${h(b.name)}</b><small>${b.active!==false?"เปิดใช้งาน":"ปิดใช้งาน"}</small><div class="action-row"><button class="ghost small" data-rename-branch="${h(b.id)}">แก้ชื่อ</button><button class="${b.active!==false?"warn":"secondary"} small" data-toggle-branch="${h(b.id)}">${b.active!==false?"ปิดใช้งาน":"เปิดใช้งาน"}</button></div></div>`).join("")}</div></div>`; }
function teaManagement() { return `<div class="card"><h3>จัดการรายการชา</h3><form id="addTeaForm" class="stack"><label>ชื่อชาใหม่ <input id="teaName" placeholder="ชื่อชา"></label><button class="primary" ${writeDisabledAttr()}>เพิ่มรายการชา</button></form><div class="mt">${state.teas.map(t=>`<div class="audit-line"><b>${h(t.displayName)}</b><small>${t.active!==false?"เปิดใช้งาน":"ปิดใช้งาน"} · ขนาด: ${(t.sizeIds||[]).map(getSizeLabel).join(", ")}</small><div class="action-row"><button class="ghost small" data-rename-tea="${h(t.id)}">แก้ชื่อ</button><button class="${t.active!==false?"warn":"secondary"} small" data-toggle-tea="${h(t.id)}">${t.active!==false?"ปิดใช้งาน":"เปิดใช้งาน"}</button><button class="ghost small" data-tea-sizes="${h(t.id)}">ขนาดของชา</button></div></div>`).join("")}</div></div>`; }
function sizeManagement() { return `<div class="card"><h3>จัดการขนาด</h3><form id="addSizeForm" class="stack"><label>กรัม <input id="sizeGrams" type="number" inputmode="numeric" placeholder="เช่น 250"></label><button class="primary" ${writeDisabledAttr()}>เพิ่มขนาด</button></form><div class="mt">${state.sizes.map(s=>`<div class="audit-line"><b>${h(s.label)}</b><small>${s.active!==false?"เปิดใช้งาน":"ปิดใช้งาน"}</small><button class="${s.active!==false?"warn":"secondary"} small" data-toggle-size="${h(s.id)}">${s.active!==false?"ปิดใช้งาน":"เปิดใช้งาน"}</button></div>`).join("")}</div></div>`; }
function thresholdSettings() { return `<div class="card"><h3>แจ้งเตือนใกล้หมด</h3><p class="muted">0 = ปิดแจ้งเตือน ตั้งได้แยก ชา + ขนาด + สาขา</p><form id="thresholdForm" class="stack">${commonFields("threshold")}<label>เตือนเมื่อเหลือน้อยกว่าหรือเท่ากับ<input id="thresholdQty" type="number" inputmode="numeric" min="0" value="0"></label><button class="primary" ${writeDisabledAttr()}>บันทึก threshold</button></form></div>`; }
function appearanceSettings() { return `<div class="card"><h3>หน้าตาระบบ</h3><form id="appearanceForm" class="stack"><label>สีธีม <input id="themeColor" type="color" value="${h(state.settings.themeColor || "#356B23")}"></label><label>ขนาดตัวอักษร<select id="fontScale">${[[.9,"เล็ก"],[1,"ปกติ"],[1.12,"ใหญ่"],[1.25,"ใหญ่มาก"]].map(([v,l])=>`<option value="${v}" ${Number(state.settings.fontScale || 1)===v?"selected":""}>${l}</option>`).join("")}</select></label><label>เปลี่ยนโลโก้ <input id="logoFile" type="file" accept="image/*"></label><button class="primary" ${writeDisabledAttr()}>บันทึกหน้าตา</button></form></div>`; }
function backupSettings() { return `<div class="card"><h3>สำรองข้อมูล</h3><p class="muted">ล่าสุด: ${state.settings.lastBackupAt ? formatDateTime(state.settings.lastBackupAt) : "-"} · ${h(state.settings.lastBackupStatus || "")}</p><div class="action-row"><button class="secondary" id="exportJsonBtn">Export JSON</button><button class="secondary" id="exportCsvBtn">Export CSV</button><button class="secondary" id="exportExcelBtn">Export Excel</button></div>${isOwner()?`<div class="mt stack"><label>Google Apps Script Web App URL<input id="backupUrl" value="${h(state.settings.googleScriptUrl || "")}" placeholder="https://script.google.com/macros/s/.../exec"></label><label>Auto Backup<select id="autoBackup">${[["off","ปิด"],["30m","ทุก 30 นาที"],["1h","ทุก 1 ชั่วโมง"],["1d","ทุกวัน"],["onChange","เมื่อมีรายการใหม่"]].map(([v,l])=>`<option value="${v}" ${state.settings.autoBackup===v?"selected":""}>${l}</option>`).join("")}</select></label><button class="primary" id="saveBackupSettingsBtn" ${writeDisabledAttr()}>บันทึกตั้งค่า Backup</button><button class="secondary" id="backupNowBtn" ${writeDisabledAttr()}>Backup ไป Google Drive ตอนนี้</button><label>Restore JSON<input id="restoreFile" type="file" accept=".json,application/json"></label><button class="danger" id="restoreBtn" ${writeDisabledAttr()}>Restore JSON</button></div>`:`<p class="muted mt">Restore เฉพาะเจ้าของเท่านั้น</p>`}</div>`; }
function auditSettings() { return `<div class="card"><h3>Audit log ล่าสุด</h3>${state.auditLogs.slice(0,30).map(a=>`<div class="audit-line"><b>${h(a.action || "-")}</b><small>${formatDateTime(a.createdAt)} · ${h(a.userName || "-")} · ${h(a.note || "")}</small></div>`).join("") || `<p class="muted">ยังไม่มี audit log</p>`}</div>`; }
function bindPageEvents(route) {
  document.querySelectorAll("[data-route-to]").forEach(el => el.addEventListener("click", () => setRoute(el.dataset.routeTo)));
  document.querySelectorAll("[data-action-route]").forEach(el => el.addEventListener("click", () => { state.ui.actionTab = el.dataset.actionRoute; setRoute("action"); }));
  document.querySelectorAll("[data-go-stock]").forEach(el => el.addEventListener("click", () => { state.ui.selectedBranchId = "all"; setRoute("stock"); }));
  document.querySelectorAll("[data-branch-tab]").forEach(el => el.addEventListener("click", () => { state.ui.selectedBranchId = el.dataset.branchTab; saveUiState(); render(); }));
  if (route === "stock") bindStockEvents(); if (route === "action") bindActionEvents(); if (route === "transfers") bindTransferEvents(); if (route === "history") bindHistoryEvents(); if (route === "settings") bindSettingsEvents();
}
function bindStockEvents() { document.getElementById("stockSearch")?.addEventListener("input", e => { state.ui.stockSearch = e.target.value; saveUiState(); scheduleRender(); }); document.getElementById("stockSizeFilter")?.addEventListener("change", e => { state.ui.sizeFilter = e.target.value; saveUiState(); render(); }); }
function bindActionEvents() {
  document.querySelectorAll("[data-action-tab]").forEach(el => el.addEventListener("click", () => { state.ui.actionTab = el.dataset.actionTab; saveUiState(); render(); }));
  document.querySelectorAll("[data-repack-mode]").forEach(el => el.addEventListener("click", () => { state.ui.repackMode = el.dataset.repackMode; saveUiState(); render(); }));
  document.querySelectorAll(".quick-buttons button").forEach(btn => btn.addEventListener("click", e => { const wrap = e.target.closest(".quick-buttons"); adjustQty(wrap.dataset.qtyFor, Number(e.target.dataset.delta)); }));
  document.querySelectorAll("select[data-size-target]").forEach(sel => sel.addEventListener("change", () => updateSizeSelectForTea(sel)));
  document.getElementById("addForm")?.addEventListener("submit", handleAdd); document.getElementById("reduceForm")?.addEventListener("submit", handleReduce); document.getElementById("countForm")?.addEventListener("submit", handleCount); document.getElementById("transferForm")?.addEventListener("submit", handleTransferCreate); document.getElementById("repackSimpleForm")?.addEventListener("submit", handleRepackSimple); document.getElementById("repackConvertForm")?.addEventListener("submit", handleRepackConvert);
  ["repackFromQty","repackToQty","repackFromSize","repackToSize"].forEach(id => document.getElementById(id)?.addEventListener("input", updateGramCheck)); updateGramCheck();
}
function bindTransferEvents() { document.querySelectorAll("[data-confirm-transfer]").forEach(btn => btn.addEventListener("click", () => confirmTransfer(btn.dataset.confirmTransfer, true))); document.querySelectorAll("[data-reject-transfer]").forEach(btn => btn.addEventListener("click", () => promptRejectTransfer(btn.dataset.rejectTransfer))); }
function bindHistoryEvents() {
  ["historyRange","historyBranch","historyType"].forEach(id => document.getElementById(id)?.addEventListener("change", e => { if (id === "historyRange") state.ui.historyRange = e.target.value; if (id === "historyBranch") state.ui.historyBranch = e.target.value; if (id === "historyType") state.ui.historyType = e.target.value; saveUiState(); render(); }));
  document.getElementById("historySearch")?.addEventListener("input", e => { state.ui.historySearch = e.target.value; saveUiState(); scheduleRender(); });
  document.getElementById("historyFrom")?.addEventListener("change", e => { state.ui.historyFrom = e.target.value; saveUiState(); render(); }); document.getElementById("historyTo")?.addEventListener("change", e => { state.ui.historyTo = e.target.value; saveUiState(); render(); });
  document.querySelectorAll("[data-toggle-hidden]").forEach(btn => btn.addEventListener("click", () => toggleHistoryHidden(btn.dataset.toggleHidden)));
}
function bindSettingsEvents() {
  document.getElementById("pinForm")?.addEventListener("submit", handleChangePin); document.getElementById("addUserForm")?.addEventListener("submit", handleAddUser); document.getElementById("addBranchForm")?.addEventListener("submit", handleAddBranch); document.getElementById("addTeaForm")?.addEventListener("submit", handleAddTea); document.getElementById("addSizeForm")?.addEventListener("submit", handleAddSize); document.getElementById("thresholdForm")?.addEventListener("submit", handleThreshold); document.getElementById("appearanceForm")?.addEventListener("submit", handleAppearance);
  document.getElementById("exportJsonBtn")?.addEventListener("click", exportJSON); document.getElementById("exportCsvBtn")?.addEventListener("click", exportCSV); document.getElementById("exportExcelBtn")?.addEventListener("click", exportExcel); document.getElementById("saveBackupSettingsBtn")?.addEventListener("click", saveBackupSettings); document.getElementById("backupNowBtn")?.addEventListener("click", () => backupToGoogleDrive(true)); document.getElementById("restoreBtn")?.addEventListener("click", restoreJSON);
  document.querySelectorAll("[data-edit-user]").forEach(btn => btn.addEventListener("click", () => promptEditUser(btn.dataset.editUser))); document.querySelectorAll("[data-disable-user]").forEach(btn => btn.addEventListener("click", () => disableUser(btn.dataset.disableUser))); document.querySelectorAll("[data-rename-branch]").forEach(btn => btn.addEventListener("click", () => promptRenameBranch(btn.dataset.renameBranch))); document.querySelectorAll("[data-toggle-branch]").forEach(btn => btn.addEventListener("click", () => toggleBranch(btn.dataset.toggleBranch))); document.querySelectorAll("[data-rename-tea]").forEach(btn => btn.addEventListener("click", () => promptRenameTea(btn.dataset.renameTea))); document.querySelectorAll("[data-toggle-tea]").forEach(btn => btn.addEventListener("click", () => toggleTea(btn.dataset.toggleTea))); document.querySelectorAll("[data-tea-sizes]").forEach(btn => btn.addEventListener("click", () => promptTeaSizes(btn.dataset.teaSizes))); document.querySelectorAll("[data-toggle-size]").forEach(btn => btn.addEventListener("click", () => toggleSize(btn.dataset.toggleSize)));
}
async function handleAdd(e) { e.preventDefault(); const p = { type: val("addType"), branchId: val("addBranch"), teaId: val("addTea"), sizeId: val("addSize"), qty: numberVal("addQty"), actionDate: val("addDate"), note: val("addNote") }; if (!validateCommon(p)) return; await mutateStock({ ...p, delta: p.qty, typeLabel: TX_LABEL[p.type] }); }
async function handleReduce(e) { e.preventDefault(); const p = { type: val("reduceType"), branchId: val("reduceBranch"), teaId: val("reduceTea"), sizeId: val("reduceSize"), qty: numberVal("reduceQty"), actionDate: val("reduceDate"), note: val("reduceNote") }; if (!validateCommon(p)) return; if (p.type === "stock_cut" && !p.note.trim()) return toast("ตัด stock ต้องระบุเหตุผล", "error"); await mutateStock({ ...p, delta: -p.qty, typeLabel: TX_LABEL[p.type] }); }
async function handleCount(e) { e.preventDefault(); const p = { type: "count", branchId: val("countBranch"), teaId: val("countTea"), sizeId: val("countSize"), qty: numberVal("countQty"), actionDate: val("countDate"), note: val("countNote") }; if (!validateCommon(p, true)) return; const current = getStockQty(p.branchId, p.teaId, p.sizeId); const diff = p.qty - current; if (diff < -5 && !p.note.trim()) return toast("ยอดลดลงมาก กรุณาระบุหมายเหตุ", "error"); await setStockCount({ ...p, beforeQty: current, afterQty: p.qty, diff }); }
async function handleTransferCreate(e) { e.preventDefault(); const p = { fromBranchId: val("transferFrom"), toBranchId: val("transferTo"), teaId: val("transferTea"), sizeId: val("transferSize"), qty: numberVal("transferQty"), actionDate: val("transferDate"), note: val("transferNote") }; if (p.fromBranchId === p.toBranchId) return toast("สาขาต้นทางและปลายทางต้องไม่ใช่สาขาเดียวกัน", "error"); if (!validateCommon({ ...p, branchId: p.fromBranchId })) return; if (!await confirmDialog("ยืนยันส่งของ?", `ระบบจะลด stock ต้นทาง ${getBranchName(p.fromBranchId)} ทันที และรอปลายทางยืนยัน`)) return; await createTransfer(p); }
async function handleRepackSimple(e) { e.preventDefault(); const p = { type: "repack_add", branchId: val("repackSimpleBranch"), teaId: val("repackSimpleTea"), sizeId: val("repackSimpleSize"), qty: numberVal("repackSimpleQty"), actionDate: val("repackSimpleDate"), note: val("repackSimpleNote") }; if (!validateCommon(p)) return; await mutateStock({ ...p, delta: p.qty, typeLabel: TX_LABEL[p.type] }); }
async function handleRepackConvert(e) { e.preventDefault(); const p = { type: "repack_convert", branchId: val("repackConvertBranch"), teaId: val("repackConvertTea"), fromSizeId: val("repackFromSize"), fromQty: numberVal("repackFromQty"), toSizeId: val("repackToSize"), toQty: numberVal("repackToQty"), actionDate: val("repackConvertDate"), note: val("repackConvertNote") }; if (!p.branchId || !p.teaId || !p.fromSizeId || !p.toSizeId) return toast("กรุณาเลือกข้อมูลให้ครบ", "error"); if (p.fromSizeId === p.toSizeId) return toast("ขนาดต้นทางและปลายทางต้องไม่เหมือนกัน", "error"); if (!validPositiveInt(p.fromQty) || !validPositiveInt(p.toQty)) return toast("จำนวนต้องเป็นเลขจำนวนเต็มมากกว่า 0", "error"); const gramsFrom = (sizeById(p.fromSizeId)?.grams || 0) * p.fromQty; const gramsTo = (sizeById(p.toSizeId)?.grams || 0) * p.toQty; const diffPercent = gramsFrom ? Math.abs(gramsFrom - gramsTo) / gramsFrom * 100 : 0; if (diffPercent > 8 && !p.note.trim()) return toast("กรัมรวมต่างกันมากกว่า 8% กรุณาระบุหมายเหตุ", "error"); await repackConvert(p); }
function validateCommon(p, allowZero = false) { if (!state.online) return toast("ออฟไลน์อยู่ กรุณาต่ออินเตอร์เน็ตก่อน", "error"), false; if (!p.branchId || !p.teaId || !p.sizeId || !p.actionDate) return toast("กรุณากรอกข้อมูลให้ครบ", "error"), false; if (allowZero ? !validNonNegativeInt(p.qty) : !validPositiveInt(p.qty)) return toast("จำนวนต้องเป็นเลขจำนวนเต็มที่ถูกต้อง", "error"), false; if (!canAccessBranch(p.branchId)) return toast("user นี้ไม่มีสิทธิ์ทำรายการสาขานี้", "error"), false; return true; }
async function mutateStock(p) {
  return runBusy(async () => {
    const tid = makeId("tx"), now = new Date().toISOString();
    if (state.mode === "local") { const s = ensureLocalStock(p.branchId, p.teaId, p.sizeId); const before = Number(s.qty || 0), after = before + Number(p.delta || 0); if (after < 0) throw new Error("จำนวนคงเหลือไม่พอ ห้ามบันทึกให้ติดลบ"); s.qty = after; s.updatedAt = now; state.transactions.unshift(transactionDoc(tid, p, before, after, now)); persistLocal(); render(); toast("บันทึกสำเร็จ", "ok"); maybeAutoBackupOnChange(); return; }
    const stockRef = doc(db, STOCK_COLLECTION, stockDocId(p.branchId, p.teaId, p.sizeId)), txRef = doc(db, "transactions", tid);
    await runTransaction(db, async tr => { const snap = await tr.get(stockRef); const before = snap.exists() ? Number(snap.data().qty || 0) : 0; const after = before + Number(p.delta || 0); if (after < 0) throw new Error("จำนวนคงเหลือไม่พอ ห้ามบันทึกให้ติดลบ"); tr.set(stockRef, { id: stockDocId(p.branchId, p.teaId, p.sizeId), branchId: p.branchId, teaId: p.teaId, sizeId: p.sizeId, qty: after, threshold: snap.exists() ? Number(snap.data().threshold || 0) : 0, updatedAt: serverTimestamp() }, { merge: true }); tr.set(txRef, transactionDoc(tid, p, before, after, now)); });
    await audit("stock_mutation", `${p.typeLabel} ${getTeaName(p.teaId)} ${getSizeLabel(p.sizeId)} ${p.qty}`); toast("บันทึกสำเร็จ", "ok"); maybeAutoBackupOnChange();
  });
}
function transactionDoc(tid, p, before, after, now) { return { id: tid, transactionId: tid, type: p.type, typeLabel: p.typeLabel || TX_LABEL[p.type] || p.type, status: "completed", branchId: p.branchId, branchName: getBranchName(p.branchId), teaId: p.teaId, teaName: getTeaName(p.teaId), sizeId: p.sizeId, sizeLabel: getSizeLabel(p.sizeId), qty: Number(p.qty || Math.abs(p.delta || 0)), delta: Number(p.delta || 0), beforeQty: before, afterQty: after, actionDate: p.actionDate, savedAt: now, userId: state.currentUser.id, userName: state.currentUser.displayName, userRole: state.currentUser.role, note: p.note || "", device: navigator.userAgent, hidden: false, createdAt: now, updatedAt: now }; }
async function setStockCount(p) {
  return runBusy(async () => { const tid = makeId("tx"), now = new Date().toISOString(); const txDoc = transactionDoc(tid, { ...p, delta: p.diff, typeLabel: "นับใหม่" }, p.beforeQty, p.afterQty, now); txDoc.diff = p.diff;
    if (state.mode === "local") { const s = ensureLocalStock(p.branchId, p.teaId, p.sizeId); s.qty = p.afterQty; s.updatedAt = now; state.transactions.unshift(txDoc); persistLocal(); render(); toast("บันทึกนับใหม่สำเร็จ", "ok"); maybeAutoBackupOnChange(); return; }
    const stockRef = doc(db, STOCK_COLLECTION, stockDocId(p.branchId, p.teaId, p.sizeId)), txRef = doc(db, "transactions", tid);
    await runTransaction(db, async tr => { const snap = await tr.get(stockRef); const before = snap.exists() ? Number(snap.data().qty || 0) : 0; const diff = p.afterQty - before; tr.set(stockRef, { id: stockDocId(p.branchId, p.teaId, p.sizeId), branchId: p.branchId, teaId: p.teaId, sizeId: p.sizeId, qty: p.afterQty, threshold: snap.exists() ? Number(snap.data().threshold || 0) : 0, updatedAt: serverTimestamp() }, { merge: true }); tr.set(txRef, { ...txDoc, beforeQty: before, afterQty: p.afterQty, diff, delta: diff }); });
    await audit("count_stock", `${getTeaName(p.teaId)} ${getSizeLabel(p.sizeId)} = ${p.afterQty}`); toast("บันทึกนับใหม่สำเร็จ", "ok"); maybeAutoBackupOnChange();
  });
}
async function createTransfer(p) {
  return runBusy(async () => { const transferId = makeId("trf"), txId = makeId("tx"), now = new Date().toISOString();
    if (state.mode === "local") { const s = ensureLocalStock(p.fromBranchId, p.teaId, p.sizeId); const before = Number(s.qty || 0), after = before - p.qty; if (after < 0) throw new Error("จำนวนคงเหลือต้นทางไม่พอ"); s.qty = after; s.updatedAt = now; state.transferRequests.unshift(transferDoc(transferId, p, now, before, after)); state.transactions.unshift(transactionDoc(txId, { ...p, branchId: p.fromBranchId, type: "transfer_out", typeLabel: "ส่งให้สาขาอื่น", delta: -p.qty }, before, after, now)); persistLocal(); render(); toast("ส่งของแล้ว รอปลายทางยืนยัน", "ok"); maybeAutoBackupOnChange(); return; }
    const stockRef = doc(db, STOCK_COLLECTION, stockDocId(p.fromBranchId, p.teaId, p.sizeId)), transferRef = doc(db, "transferRequests", transferId), txRef = doc(db, "transactions", txId);
    await runTransaction(db, async tr => { const snap = await tr.get(stockRef); const before = snap.exists() ? Number(snap.data().qty || 0) : 0; const after = before - p.qty; if (after < 0) throw new Error("จำนวนคงเหลือต้นทางไม่พอ"); tr.set(stockRef, { id: stockDocId(p.fromBranchId, p.teaId, p.sizeId), branchId: p.fromBranchId, teaId: p.teaId, sizeId: p.sizeId, qty: after, threshold: snap.exists() ? Number(snap.data().threshold || 0) : 0, updatedAt: serverTimestamp() }, { merge: true }); tr.set(transferRef, transferDoc(transferId, p, now, before, after)); tr.set(txRef, transactionDoc(txId, { ...p, branchId: p.fromBranchId, type: "transfer_out", typeLabel: "ส่งให้สาขาอื่น", delta: -p.qty }, before, after, now)); });
    await audit("create_transfer", `${getBranchName(p.fromBranchId)} → ${getBranchName(p.toBranchId)} ${getTeaName(p.teaId)} ${p.qty}`); toast("ส่งของแล้ว รอปลายทางยืนยัน", "ok"); maybeAutoBackupOnChange();
  });
}
function transferDoc(id, p, now, before, after) { return { id, transferId: id, status: "pending", fromBranchId: p.fromBranchId, fromBranchName: getBranchName(p.fromBranchId), toBranchId: p.toBranchId, toBranchName: getBranchName(p.toBranchId), teaId: p.teaId, teaName: getTeaName(p.teaId), sizeId: p.sizeId, sizeLabel: getSizeLabel(p.sizeId), qty: p.qty, sourceBeforeQty: before, sourceAfterQty: after, actionDate: p.actionDate, note: p.note || "", createdBy: state.currentUser.id, createdByName: state.currentUser.displayName, createdByRole: state.currentUser.role, createdAt: now, updatedAt: now, hidden: false }; }
async function confirmTransfer(id, exact, receivedQty = null, receiveNote = "") {
  const t = state.transferRequests.find(x => x.id === id); if (!t) return toast("ไม่พบรายการโอน", "error"); if (!canConfirmTransfer(t)) return toast("ไม่มีสิทธิ์ยืนยันรายการนี้", "error"); const qtyToReceive = exact ? Number(t.qty) : Number(receivedQty); if (!exact && !validNonNegativeInt(qtyToReceive)) return toast("จำนวนที่ได้รับจริงไม่ถูกต้อง", "error"); const newStatus = exact ? "completed" : "review_required";
  return runBusy(async () => { const now = new Date().toISOString(), txId = makeId("tx");
    if (state.mode === "local") { if (exact) { const s = ensureLocalStock(t.toBranchId, t.teaId, t.sizeId); const before = Number(s.qty || 0), after = before + Number(t.qty); s.qty = after; s.updatedAt = now; state.transactions.unshift(transactionDoc(txId, { branchId: t.toBranchId, teaId: t.teaId, sizeId: t.sizeId, type: "transfer_in", typeLabel: "รับโอนเข้า", qty: t.qty, delta: t.qty, actionDate: todayISO(), note: `รับจาก ${getBranchName(t.fromBranchId)}` }, before, after, now)); } else { state.transactions.unshift({ ...transactionDoc(txId, { branchId: t.toBranchId, teaId: t.teaId, sizeId: t.sizeId, type: "transfer_review", typeLabel: "โอนผิดปกติ", qty: qtyToReceive, delta: 0, actionDate: todayISO(), note: receiveNote }, 0, 0, now), status: "review_required" }); } Object.assign(t, { status: newStatus, receivedQty: qtyToReceive, receiveNote, receivedBy: state.currentUser.id, receivedByName: state.currentUser.displayName, receivedAt: now, updatedAt: now }); persistLocal(); render(); toast(exact ? "รับเข้าสต๊อกแล้ว" : "บันทึกไม่ตรง ส่งให้ตรวจสอบแล้ว", exact ? "ok" : "warn"); maybeAutoBackupOnChange(); return; }
    const transferRef = doc(db, "transferRequests", id), destStockRef = doc(db, STOCK_COLLECTION, stockDocId(t.toBranchId, t.teaId, t.sizeId)), txRef = doc(db, "transactions", txId);
    await runTransaction(db, async tr => { const trSnap = await tr.get(transferRef); if (!trSnap.exists()) throw new Error("ไม่พบรายการโอน"); if (trSnap.data().status !== "pending") throw new Error("รายการนี้ถูกจัดการไปแล้ว"); let before = 0, after = 0; if (exact) { const sSnap = await tr.get(destStockRef); before = sSnap.exists() ? Number(sSnap.data().qty || 0) : 0; after = before + Number(t.qty); tr.set(destStockRef, { id: stockDocId(t.toBranchId, t.teaId, t.sizeId), branchId: t.toBranchId, teaId: t.teaId, sizeId: t.sizeId, qty: after, threshold: sSnap.exists() ? Number(sSnap.data().threshold || 0) : 0, updatedAt: serverTimestamp() }, { merge: true }); } tr.update(transferRef, { status: newStatus, receivedQty: qtyToReceive, receiveNote, receivedBy: state.currentUser.id, receivedByName: state.currentUser.displayName, receivedAt: now, updatedAt: serverTimestamp() }); tr.set(txRef, { ...transactionDoc(txId, { branchId: t.toBranchId, teaId: t.teaId, sizeId: t.sizeId, type: exact ? "transfer_in" : "transfer_review", typeLabel: exact ? "รับโอนเข้า" : "โอนผิดปกติ", qty: qtyToReceive, delta: exact ? Number(t.qty) : 0, actionDate: todayISO(), note: receiveNote || `รับจาก ${getBranchName(t.fromBranchId)}` }, before, after, now), status: newStatus }); });
    await audit("confirm_transfer", `${id} status=${newStatus}`); toast(exact ? "รับเข้าสต๊อกแล้ว" : "บันทึกไม่ตรง ส่งให้ตรวจสอบแล้ว", exact ? "ok" : "warn"); maybeAutoBackupOnChange();
  });
}
async function promptRejectTransfer(id) { const t = state.transferRequests.find(x => x.id === id); if (!t) return; const ok = await modal("ไม่ตรง/ปฏิเสธรายการโอน", `<label>จำนวนที่ได้รับจริง<input id="rejectQty" type="number" inputmode="numeric" min="0" value="${h(t.qty)}"></label><label>หมายเหตุ<textarea id="rejectNote" placeholder="เช่น ได้รับไม่ครบ/ถุงชำรุด"></textarea></label>`, "บันทึกส่งตรวจสอบ"); if (!ok) return; if (!val("rejectNote").trim()) return toast("กรุณาระบุหมายเหตุ", "error"); await confirmTransfer(id, false, numberVal("rejectQty"), val("rejectNote")); }
async function repackConvert(p) {
  return runBusy(async () => { const now = new Date().toISOString(), txId = makeId("tx");
    if (state.mode === "local") { const from = ensureLocalStock(p.branchId, p.teaId, p.fromSizeId), to = ensureLocalStock(p.branchId, p.teaId, p.toSizeId); const beforeFrom = Number(from.qty||0), afterFrom = beforeFrom - p.fromQty; if (afterFrom < 0) throw new Error("จำนวนขนาดต้นทางไม่พอ"); const beforeTo = Number(to.qty||0), afterTo = beforeTo + p.toQty; from.qty = afterFrom; to.qty = afterTo; from.updatedAt = now; to.updatedAt = now; state.transactions.unshift(repackTxDoc(txId, p, beforeFrom, afterFrom, beforeTo, afterTo, now)); persistLocal(); render(); toast("บันทึกรีแพคแปลงขนาดสำเร็จ", "ok"); maybeAutoBackupOnChange(); return; }
    const fromRef = doc(db, STOCK_COLLECTION, stockDocId(p.branchId, p.teaId, p.fromSizeId)), toRef = doc(db, STOCK_COLLECTION, stockDocId(p.branchId, p.teaId, p.toSizeId)), txRef = doc(db, "transactions", txId);
    await runTransaction(db, async tr => { const fromSnap = await tr.get(fromRef), toSnap = await tr.get(toRef); const beforeFrom = fromSnap.exists() ? Number(fromSnap.data().qty || 0) : 0; const afterFrom = beforeFrom - p.fromQty; if (afterFrom < 0) throw new Error("จำนวนขนาดต้นทางไม่พอ"); const beforeTo = toSnap.exists() ? Number(toSnap.data().qty || 0) : 0; const afterTo = beforeTo + p.toQty; tr.set(fromRef, { id: stockDocId(p.branchId, p.teaId, p.fromSizeId), branchId: p.branchId, teaId: p.teaId, sizeId: p.fromSizeId, qty: afterFrom, threshold: fromSnap.exists()?Number(fromSnap.data().threshold||0):0, updatedAt: serverTimestamp() }, { merge: true }); tr.set(toRef, { id: stockDocId(p.branchId, p.teaId, p.toSizeId), branchId: p.branchId, teaId: p.teaId, sizeId: p.toSizeId, qty: afterTo, threshold: toSnap.exists()?Number(toSnap.data().threshold||0):0, updatedAt: serverTimestamp() }, { merge: true }); tr.set(txRef, repackTxDoc(txId, p, beforeFrom, afterFrom, beforeTo, afterTo, now)); });
    await audit("repack_convert", `${getTeaName(p.teaId)} ${getSizeLabel(p.fromSizeId)} → ${getSizeLabel(p.toSizeId)}`); toast("บันทึกรีแพคแปลงขนาดสำเร็จ", "ok"); maybeAutoBackupOnChange();
  });
}
function repackTxDoc(txId, p, beforeFrom, afterFrom, beforeTo, afterTo, now) { const gramsFrom = (sizeById(p.fromSizeId)?.grams || 0) * p.fromQty, gramsTo = (sizeById(p.toSizeId)?.grams || 0) * p.toQty; return { id: txId, transactionId: txId, type: "repack_convert", typeLabel: "รีแพคแปลงขนาด", status: "completed", branchId: p.branchId, branchName: getBranchName(p.branchId), teaId: p.teaId, teaName: getTeaName(p.teaId), actionDate: p.actionDate, savedAt: now, userId: state.currentUser.id, userName: state.currentUser.displayName, userRole: state.currentUser.role, note: p.note || "", device: navigator.userAgent, hidden: false, gramsFrom, gramsTo, gramDiff: gramsTo - gramsFrom, items: [{ branchId: p.branchId, teaId: p.teaId, sizeId: p.fromSizeId, sizeLabel: getSizeLabel(p.fromSizeId), qty: p.fromQty, delta: -p.fromQty, beforeQty: beforeFrom, afterQty: afterFrom }, { branchId: p.branchId, teaId: p.teaId, sizeId: p.toSizeId, sizeLabel: getSizeLabel(p.toSizeId), qty: p.toQty, delta: p.toQty, beforeQty: beforeTo, afterQty: afterTo }], createdAt: now, updatedAt: now }; }
async function handleChangePin(e) { e.preventDefault(); const oldPin = onlyDigits(val("oldPin")), newPin = onlyDigits(val("newPin")); if (oldPin !== String(state.currentUser.pin)) return toast("PIN เดิมไม่ถูกต้อง", "error"); if (!/^\d{4}$/.test(newPin)) return toast("PIN ใหม่ต้องเป็นตัวเลข 4 ตัว", "error"); await saveDoc("users", state.currentUser.id, { pin: newPin, requirePinChange: false, updatedAt: nowOrServer() }, true); state.currentUser.pin = newPin; state.currentUser.requirePinChange = false; await audit("change_pin", "เปลี่ยน PIN ตัวเอง"); toast("เปลี่ยน PIN สำเร็จ", "ok"); }
async function handleAddUser(e) { e.preventDefault(); if (!canManageUsers()) return; const name = val("newUserName").trim(), role = val("newUserRole"), pin = onlyDigits(val("newUserPin")), branchId = val("newUserBranch"); if (!name) return toast("กรุณาใส่ชื่อ user", "error"); if (!/^\d{4}$/.test(pin)) return toast("PIN ต้องเป็นตัวเลข 4 ตัว", "error"); if (!isOwner() && role !== "employee") return toast("ผู้จัดการเพิ่มได้เฉพาะพนักงาน", "error"); const id = makeSlugId("user", name); await saveDoc("users", id, { id, displayName: name, role, pin, branchIds: role === "employee" ? [branchId] : activeBranches().map(b => b.id), active: true, requirePinChange: true, createdAt: new Date().toISOString(), updatedAt: nowOrServer() }); await audit("add_user", name); toast("เพิ่ม user สำเร็จ", "ok"); }
async function promptEditUser(id) { const u = state.users.find(x => x.id === id); if (!u) return; if (!isOwner() && u.role !== "employee") return toast("ผู้จัดการแก้ได้เฉพาะพนักงาน", "error"); const ok = await modal("แก้ไข user / reset PIN", `<label>ชื่อ<input id="editUserName" value="${h(u.displayName)}"></label><label>บทบาท<select id="editUserRole">${isOwner()?`<option value="owner" ${u.role==="owner"?"selected":""}>เจ้าของ</option><option value="manager" ${u.role==="manager"?"selected":""}>ผู้จัดการ</option>`:""}<option value="employee" ${u.role==="employee"?"selected":""}>พนักงาน</option></select></label><label>สาขาหลัก<select id="editUserBranch">${activeBranches().map(b=>`<option value="${h(b.id)}" ${(u.branchIds||[])[0]===b.id?"selected":""}>${h(b.name)}</option>`).join("")}</select></label><label>Reset PIN<input id="editUserPin" inputmode="numeric" maxlength="4" value="${h(u.pin || "1234")}"></label>`, "บันทึก"); if (!ok) return; const role = val("editUserRole"), pin = onlyDigits(val("editUserPin")); if (!isOwner() && role !== "employee") return toast("ผู้จัดการแก้ได้เฉพาะพนักงาน", "error"); if (!/^\d{4}$/.test(pin)) return toast("PIN ต้องเป็นตัวเลข 4 ตัว", "error"); await saveDoc("users", id, { displayName: val("editUserName").trim(), role, pin, branchIds: role === "employee" ? [val("editUserBranch")] : activeBranches().map(b => b.id), requirePinChange: true, updatedAt: nowOrServer() }, true); await audit("edit_user", id); toast("บันทึก user สำเร็จ", "ok"); }
async function disableUser(id) { const u = state.users.find(x => x.id === id); if (!u || u.id === state.currentUser.id) return; if (!isOwner() && u.role !== "employee") return toast("ผู้จัดการปิดได้เฉพาะพนักงาน", "error"); if (!await confirmDialog("ปิดใช้งาน user?", `user ${u.displayName} จะ login ไม่ได้`)) return; await saveDoc("users", id, { active: false, updatedAt: nowOrServer() }, true); await audit("disable_user", u.displayName); toast("ปิดใช้งานแล้ว", "ok"); }
async function handleAddBranch(e) { e.preventDefault(); const name = val("branchName").trim(); if (!name) return toast("กรุณาใส่ชื่อสาขา", "error"); const id = makeSlugId("branch", name); await saveDoc("branches", id, { id, name, active: true, order: state.branches.length + 1, createdAt: new Date().toISOString(), updatedAt: nowOrServer() }); await audit("add_branch", name); toast("เพิ่มสาขาแล้ว", "ok"); }
async function promptRenameBranch(id) { const b = branchById(id); const name = prompt("ชื่อสาขาใหม่", b?.name || ""); if (!name) return; await saveDoc("branches", id, { name: name.trim(), updatedAt: nowOrServer() }, true); await audit("rename_branch", name); }
async function toggleBranch(id) { const b = branchById(id); await saveDoc("branches", id, { active: b.active === false, updatedAt: nowOrServer() }, true); await audit("toggle_branch", id); }
async function handleAddTea(e) { e.preventDefault(); if (!canManageTea()) return; const name = val("teaName").trim(); if (!name) return toast("กรุณาใส่ชื่อชา", "error"); const id = makeSlugId("tea", name); await saveDoc("teas", id, { id, displayName: name, active: true, order: state.teas.length + 1, sizeIds: activeSizes().map(s => s.id), createdAt: new Date().toISOString(), updatedAt: nowOrServer() }); await audit("add_tea", name); toast("เพิ่มรายการชาแล้ว", "ok"); }
async function promptRenameTea(id) { const t = teaById(id); const name = prompt("ชื่อชาใหม่", t?.displayName || ""); if (!name) return; await saveDoc("teas", id, { displayName: name.trim(), updatedAt: nowOrServer() }, true); await audit("rename_tea", name); }
async function toggleTea(id) { const t = teaById(id); await saveDoc("teas", id, { active: t.active === false, updatedAt: nowOrServer() }, true); await audit("toggle_tea", id); }
async function promptTeaSizes(id) { const t = teaById(id); if (!t) return; const html = activeSizes().map(s => `<label class="check-row"><span>${h(s.label)}</span><input type="checkbox" class="tea-size-check" value="${h(s.id)}" ${(t.sizeIds||[]).includes(s.id)?"checked":""}></label>`).join(""); const ok = await modal(`ขนาดของ ${t.displayName}`, html, "บันทึก"); if (!ok) return; const sizeIds = [...document.querySelectorAll(".tea-size-check:checked")].map(x => x.value); if (!sizeIds.length) return toast("ต้องเลือกอย่างน้อย 1 ขนาด", "error"); await saveDoc("teas", id, { sizeIds, updatedAt: nowOrServer() }, true); await audit("tea_sizes", t.displayName); }
async function handleAddSize(e) { e.preventDefault(); const grams = numberVal("sizeGrams"); if (!validPositiveInt(grams)) return toast("กรัมต้องเป็นเลขจำนวนเต็มมากกว่า 0", "error"); const id = `size_${grams}`; await saveDoc("sizes", id, { id, label: `${grams} gm`, grams, active: true, order: grams, createdAt: new Date().toISOString(), updatedAt: nowOrServer() }); await audit("add_size", `${grams} gm`); toast("เพิ่มขนาดแล้ว", "ok"); }
async function toggleSize(id) { const s = sizeById(id); await saveDoc("sizes", id, { active: s.active === false, updatedAt: nowOrServer() }, true); await audit("toggle_size", id); }
async function handleThreshold(e) { e.preventDefault(); const branchId = val("thresholdBranch"), teaId = val("thresholdTea"), sizeId = val("thresholdSize"), threshold = numberVal("thresholdQty"); if (!validNonNegativeInt(threshold)) return toast("Threshold ต้องเป็นเลข 0 ขึ้นไป", "error"); const id = stockDocId(branchId, teaId, sizeId); await saveDoc(STOCK_COLLECTION, id, { id, branchId, teaId, sizeId, qty: getStockQty(branchId, teaId, sizeId), threshold, updatedAt: nowOrServer() }, true); await audit("set_threshold", `${getBranchName(branchId)} ${getTeaName(teaId)} ${getSizeLabel(sizeId)} <= ${threshold}`); toast("บันทึกแจ้งเตือนใกล้หมดแล้ว", "ok"); }
async function handleAppearance(e) { e.preventDefault(); let logoDataUrl = state.settings.logoDataUrl || ""; const file = document.getElementById("logoFile")?.files?.[0]; if (file) logoDataUrl = await readFileAsDataURL(file); await saveSettings({ themeColor: val("themeColor"), fontScale: Number(val("fontScale")), logoDataUrl, updatedAt: nowOrServer() }); await audit("appearance", "ปรับหน้าตาระบบ"); toast("บันทึกหน้าตาแล้ว", "ok"); }
async function toggleHistoryHidden(id) { if (!isOwner()) return; const tx = state.transactions.find(t => t.id === id); if (!tx) return; await saveDoc("transactions", id, { hidden: !tx.hidden, updatedAt: nowOrServer() }, true); await audit(tx.hidden ? "unhide_history" : "hide_history", id); }
function buildBackupPayload() { return { app: "Love Matcha Stock", version: VERSION, exportedAt: new Date().toISOString(), exportedBy: state.currentUser ? { id: state.currentUser.id, displayName: state.currentUser.displayName, role: state.currentUser.role } : null, data: { users: state.users, branches: state.branches, teas: state.teas, sizes: state.sizes, stockByBranch: state.stock, transactions: state.transactions, transferRequests: state.transferRequests, settings: state.settings, auditLogs: state.auditLogs } }; }
function exportJSON() { downloadFile(`love-matcha-stock-backup-${dateStamp()}.json`, JSON.stringify(buildBackupPayload(), null, 2), "application/json"); toast("Export JSON แล้ว", "ok"); }
function exportCSV() { const rows = [["branch","tea","size","qty","threshold"]]; state.stock.forEach(s => rows.push([getBranchName(s.branchId), getTeaName(s.teaId), getSizeLabel(s.sizeId), s.qty, s.threshold || 0])); downloadFile(`love-matcha-stock-${dateStamp()}.csv`, toCSV(rows), "text/csv;charset=utf-8"); toast("Export CSV แล้ว", "ok"); }
function exportExcel() { if (!window.XLSX) return toast("ไม่พบไลบรารี Excel ให้ใช้ Export CSV แทน", "warn"); const wb = XLSX.utils.book_new(); const stockRows = state.stock.map(s => ({ สาขา: getBranchName(s.branchId), ชา: getTeaName(s.teaId), ขนาด: getSizeLabel(s.sizeId), จำนวน: Number(s.qty || 0), เตือนเมื่อเหลือไม่เกิน: Number(s.threshold || 0) })); const txRows = state.transactions.slice(0, 5000).map(tx => ({ วันที่ทำรายการ: tx.actionDate, เวลาบันทึก: tx.savedAt, สาขา: getBranchName(tx.branchId || tx.fromBranchId || tx.toBranchId), ประเภท: tx.typeLabel || TX_LABEL[tx.type] || tx.type, ชา: tx.teaName || getTeaName(tx.teaId), ขนาด: tx.sizeLabel || getSizeLabel(tx.sizeId), จำนวน: tx.qty, ก่อน: tx.beforeQty, หลัง: tx.afterQty, ผู้ทำ: tx.userName, สถานะ: tx.status, หมายเหตุ: tx.note })); XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(stockRows), "Stock"); XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(txRows), "Transactions"); XLSX.writeFile(wb, `love-matcha-stock-${dateStamp()}.xlsx`); toast("Export Excel แล้ว", "ok"); }
async function saveBackupSettings() { if (!isOwner()) return; await saveSettings({ googleScriptUrl: val("backupUrl").trim(), autoBackup: val("autoBackup"), updatedAt: nowOrServer() }); startAutoBackup(); toast("บันทึกตั้งค่า Backup แล้ว", "ok"); }
async function backupToGoogleDrive(showToast = false) { const url = state.settings.googleScriptUrl; if (!url) { if (showToast) toast("ยังไม่ได้ใส่ Google Apps Script Web App URL", "error"); return false; } try { const res = await fetch(url, { method: "POST", mode: "cors", headers: { "Content-Type": "text/plain;charset=utf-8" }, body: JSON.stringify(buildBackupPayload()) }); const text = await res.text(); let result = {}; try { result = JSON.parse(text); } catch { result = { ok: res.ok, text }; } if (!res.ok || result.ok === false) throw new Error(result.error || text || "Backup failed"); await saveSettings({ lastBackupAt: new Date().toISOString(), lastBackupStatus: "สำเร็จ", updatedAt: nowOrServer() }); if (showToast) toast("Backup ไป Google Drive สำเร็จ", "ok"); return true; } catch (err) { await saveSettings({ lastBackupAt: new Date().toISOString(), lastBackupStatus: `ล้มเหลว: ${err.message}`, updatedAt: nowOrServer() }); if (showToast) toast(`Backup ล้มเหลว: ${err.message}`, "error"); return false; } }
function startAutoBackup() { stopAutoBackup(); if (!state.currentUser || !isOwner()) return; const setting = state.settings.autoBackup || "off"; if (setting === "off" || setting === "onChange") return; const ms = setting === "30m" ? 30*60*1000 : setting === "1h" ? 60*60*1000 : 24*60*60*1000; autoBackupTimer = setInterval(() => backupToGoogleDrive(false), ms); }
function stopAutoBackup() { if (autoBackupTimer) clearInterval(autoBackupTimer); autoBackupTimer = null; }
function maybeAutoBackupOnChange() { if (isOwner() && state.settings.autoBackup === "onChange") backupToGoogleDrive(false); }
async function restoreJSON() { if (!isOwner()) return toast("Restore เฉพาะเจ้าของเท่านั้น", "error"); const file = document.getElementById("restoreFile")?.files?.[0]; if (!file) return toast("กรุณาเลือกไฟล์ JSON", "error"); const pin = prompt("ยืนยัน Restore: กรุณากรอก PIN เจ้าของ"); if (String(pin) !== String(state.currentUser.pin)) return toast("PIN ไม่ถูกต้อง", "error"); if (!await confirmDialog("ยืนยัน Restore?", "ระบบจะเขียนข้อมูลจากไฟล์เข้า Firebase/เครื่องนี้ ควร Export สำรองก่อนเสมอ")) return; const payload = JSON.parse(await file.text()); const data = payload.data || payload; await runBusy(async () => { if (state.mode === "local") { state.users = data.users || state.users; state.branches = data.branches || state.branches; state.teas = data.teas || state.teas; state.sizes = data.sizes || state.sizes; state.stock = data.stockByBranch || data.stock || state.stock; state.transactions = data.transactions || state.transactions; state.transferRequests = data.transferRequests || state.transferRequests; state.settings = { ...state.settings, ...(data.settings || {}) }; state.auditLogs = data.auditLogs || state.auditLogs; persistLocal(); render(); toast("Restore สำเร็จ", "ok"); return; } await restoreCollection("users", data.users || []); await restoreCollection("branches", data.branches || []); await restoreCollection("teas", data.teas || []); await restoreCollection("sizes", data.sizes || []); await restoreCollection(STOCK_COLLECTION, data.stockByBranch || data.stock || []); await restoreCollection("transactions", data.transactions || []); await restoreCollection("transferRequests", data.transferRequests || []); await restoreCollection("auditLogs", data.auditLogs || []); if (data.settings) await setDoc(doc(db, "settings", "global"), data.settings, { merge: true }); await audit("restore_json", file.name); toast("Restore สำเร็จ", "ok"); }); }
async function restoreCollection(col, arr) { for (const items of chunk(arr, 400)) { const batch = writeBatch(db); items.forEach(item => { const id = item.id || item.transactionId || item.transferId || makeId(col); batch.set(doc(db, col, id), { ...item, id }, { merge: true }); }); await batch.commit(); } }
async function seedFirestore() {
  if (!db) return; if (!await confirmDialog("ติดตั้งข้อมูลเริ่มต้น?", "ระบบจะสร้าง owner, สาขา, รายการชา, ขนาด และ stock ปัจจุบันจาก Excel")) return;
  await runBusy(async () => { const userSnap = await getDocs(collection(db, "users")); if (!userSnap.empty) return toast("มีข้อมูล users อยู่แล้ว ไม่ seed ซ้ำ", "warn"); const now = new Date().toISOString(); const ops = []; const owner = { id: "user_owner", displayName: "เจ้าของ", role: "owner", pin: "1234", branchIds: SEED_DATA.branches.map(b => b.id), active: true, requirePinChange: true, createdAt: now, updatedAt: now };
    ops.push(["users", owner.id, owner]); SEED_DATA.branches.forEach(b => ops.push(["branches", b.id, { ...b, createdAt: now, updatedAt: now }])); SEED_DATA.sizes.forEach(s => ops.push(["sizes", s.id, { ...s, createdAt: now, updatedAt: now }])); SEED_DATA.teas.forEach(t => ops.push(["teas", t.id, { ...t, createdAt: now, updatedAt: now }])); SEED_DATA.stock.forEach(s => { const id = stockDocId(s.branchId, s.teaId, s.sizeId); ops.push([STOCK_COLLECTION, id, { id, branchId: s.branchId, teaId: s.teaId, sizeId: s.sizeId, qty: Number(s.qty || 0), threshold: 0, updatedAt: now }]); });
    SEED_DATA.branches.forEach(branch => { const items = SEED_DATA.stock.filter(s => s.branchId === branch.id && Number(s.qty || 0) !== 0).map(s => ({ branchId: s.branchId, teaId: s.teaId, sizeId: s.sizeId, qty: Number(s.qty || 0), delta: Number(s.qty || 0), beforeQty: 0, afterQty: Number(s.qty || 0) })); ops.push(["transactions", `tx_seed_${branch.id}`, { id: `tx_seed_${branch.id}`, transactionId: `tx_seed_${branch.id}`, type: "seed_import", typeLabel: "นำเข้าจาก Excel", status: "completed", branchId: branch.id, branchName: branch.name, actionDate: todayISO(), savedAt: now, userId: "system", userName: "ระบบ", userRole: "system", note: `นำเข้า Stock ปัจจุบันจาก ${SEED_DATA.sourceWorkbook}`, hidden: false, items, createdAt: now, updatedAt: now }]); });
    ops.push(["settings", "global", defaultSettings(now)]); for (const part of chunk(ops, 430)) { const batch = writeBatch(db); part.forEach(([col, id, data]) => batch.set(doc(db, col, id), data, { merge: true })); await batch.commit(); } toast("ติดตั้งข้อมูลเริ่มต้นสำเร็จ Login ด้วย เจ้าของ / 1234", "ok"); });
}
async function saveDoc(col, id, data, merge = true) { if (!state.online) return toast("ออฟไลน์อยู่ กรุณาต่ออินเตอร์เน็ตก่อน", "error"); if (state.mode === "local") { const keyMap = { users:"users", branches:"branches", teas:"teas", sizes:"sizes", [STOCK_COLLECTION]:"stock", transactions:"transactions", transferRequests:"transferRequests", auditLogs:"auditLogs" }; const arrName = keyMap[col]; if (arrName) { const arr = state[arrName]; const idx = arr.findIndex(x => x.id === id); if (idx >= 0) arr[idx] = merge ? { ...arr[idx], ...data, id } : { ...data, id }; else arr.push({ ...data, id }); } persistLocal(); render(); return; } await setDoc(doc(db, col, id), data, { merge }); }
async function saveSettings(data) { if (state.mode === "local") { state.settings = { ...state.settings, ...data, updatedAt: new Date().toISOString() }; persistLocal(); render(); return; } await setDoc(doc(db, "settings", "global"), data, { merge: true }); }
async function audit(action, note = "") { const now = new Date().toISOString(); const item = { id: makeId("audit"), action, note, userId: state.currentUser?.id || "system", userName: state.currentUser?.displayName || "ระบบ", userRole: state.currentUser?.role || "system", createdAt: now, device: navigator.userAgent }; if (state.mode === "local") { state.auditLogs.unshift(item); persistLocal(); return; } try { await setDoc(doc(db, "auditLogs", item.id), item); } catch (err) { console.info("audit failed", err); } }
async function runBusy(fn) { if (state.busy) return; state.busy = true; render(); try { await fn(); } catch (err) { console.error(err); toast(err.message || "เกิดข้อผิดพลาด", "error"); } finally { state.busy = false; render(); } }
function activeUsers() { return state.users.filter(u => u.active !== false).sort((a,b) => String(a.displayName).localeCompare(String(b.displayName), "th")); }
function activeBranches() { return state.branches.filter(b => b.active !== false).sort((a,b) => Number(a.order || 0) - Number(b.order || 0)); }
function activeTeas() { return state.teas.filter(t => t.active !== false).sort((a,b) => Number(a.order || 0) - Number(b.order || 0)); }
function activeSizes() { return state.sizes.filter(s => s.active !== false).sort((a,b) => Number(a.order || a.grams || 0) - Number(b.order || b.grams || 0)); }
function branchById(id) { return state.branches.find(b => b.id === id); } function teaById(id) { return state.teas.find(t => t.id === id); } function sizeById(id) { return state.sizes.find(s => s.id === id); }
function getBranchName(id) { return branchById(id)?.name || id || "-"; } function getTeaName(id) { return teaById(id)?.displayName || id || "-"; } function getSizeLabel(id) { return sizeById(id)?.label || id || "-"; } function roleLabel(role) { return ROLE_LABEL[role] || role || "-"; }
function isOwner() { return state.currentUser?.role === "owner"; } function isManager() { return state.currentUser?.role === "manager"; } function canManageUsers() { return isOwner() || isManager(); } function canManageTea() { return isOwner() || isManager(); } function canManageThresholds() { return isOwner() || isManager(); } function canExportBackup() { return isOwner() || (isManager() && state.settings.managerCanExport !== false); }
function isMyBranch(branchId) { return (state.currentUser?.branchIds || []).includes(branchId); } function primaryBranchId() { return (state.currentUser?.branchIds || [])[0] || activeBranches()[0]?.id || ""; } function canAccessBranch(branchId) { return isOwner() || isManager() || isMyBranch(branchId); } function canConfirmTransfer(t) { return isOwner() || isManager() || isMyBranch(t.toBranchId); }
function sortedBranchesForUser() { const mine = new Set(state.currentUser?.branchIds || []); return activeBranches().sort((a,b) => (mine.has(a.id)?0:1) - (mine.has(b.id)?0:1) || Number(a.order||0) - Number(b.order||0)); }
function getStockQty(branchId, teaId, sizeId) { return Number(state.stock.find(s => s.branchId === branchId && s.teaId === teaId && s.sizeId === sizeId)?.qty || 0); }
function ensureLocalStock(branchId, teaId, sizeId) { const id = stockDocId(branchId, teaId, sizeId); let s = state.stock.find(x => x.id === id); if (!s) { s = { id, branchId, teaId, sizeId, qty: 0, threshold: 0, updatedAt: new Date().toISOString() }; state.stock.push(s); } return s; }
function getStockList(branchId) { const rows = [], teas = activeTeas(), sizes = activeSizes(); if (branchId === "all") { for (const tea of teas) { const allowed = tea.sizeIds || sizes.map(s=>s.id); for (const size of sizes.filter(s=>allowed.includes(s.id))) { const items = state.stock.filter(s=>s.teaId===tea.id && s.sizeId===size.id); rows.push({ teaId: tea.id, teaName: tea.displayName, sizeId: size.id, sizeLabel: size.label, qty: items.reduce((sum,s)=>sum+Number(s.qty||0),0), threshold: Math.max(0, ...items.map(s=>Number(s.threshold||0))) }); } } } else { for (const tea of teas) { const allowed = tea.sizeIds || sizes.map(s=>s.id); for (const size of sizes.filter(s=>allowed.includes(s.id))) { const d = state.stock.find(s=>s.branchId===branchId && s.teaId===tea.id && s.sizeId===size.id); rows.push({ branchId, teaId: tea.id, teaName: tea.displayName, sizeId: size.id, sizeLabel: size.label, qty: Number(d?.qty||0), threshold: Number(d?.threshold||0) }); } } } return rows; }
function aggregateTotalStock() { return getStockList("all").filter(x => Number(x.qty) !== 0).sort((a,b) => Math.abs(b.qty) - Math.abs(a.qty)); }
function lowStockItems() { return state.stock.filter(s => Number(s.threshold || 0) > 0 && Number(s.qty || 0) <= Number(s.threshold || 0)); }
function pendingTransfersForCurrentUser() { return state.transferRequests.filter(t => t.status === "pending" && canConfirmTransfer(t)); }
function filteredTransactions() { const now = new Date(); let from = "1900-01-01", to = "2999-12-31"; if (state.ui.historyRange === "today") from = to = todayISO(); else if (state.ui.historyRange === "7d") { const d = new Date(); d.setDate(d.getDate()-6); from = d.toISOString().slice(0,10); to = todayISO(); } else if (state.ui.historyRange === "month") { from = `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}-01`; to = todayISO(); } else if (state.ui.historyRange === "custom") { from = state.ui.historyFrom || todayISO(); to = state.ui.historyTo || todayISO(); } const search = (state.ui.historySearch || "").toLowerCase(); return state.transactions.filter(tx => { if (!isOwner() && tx.hidden) return false; const date = String(tx.actionDate || tx.savedAt || "").slice(0,10); if (date < from || date > to) return false; const bf = state.ui.historyBranch || "all"; if (bf !== "all" && (tx.branchId || tx.fromBranchId || tx.toBranchId) !== bf) return false; if (state.ui.historyType && tx.type !== state.ui.historyType) return false; if (search) { const text = `${tx.userName||""} ${tx.teaName || getTeaName(tx.teaId)} ${tx.sizeLabel||""} ${tx.note||""} ${tx.typeLabel||""}`.toLowerCase(); if (!text.includes(search)) return false; } return true; }); }
function groupBy(arr, key) { return arr.reduce((acc,item) => ((acc[item[key]] ||= []).push(item), acc), {}); } function sortBySize(a,b) { return Number(sizeById(a.sizeId)?.grams || 0) - Number(sizeById(b.sizeId)?.grams || 0); }
function updateSizeSelectForTea(sel) { const tea = teaById(sel.value); const targetIds = String(sel.dataset.sizeTarget || "").split(",").map(x=>x.trim()).filter(Boolean); const sizes = activeSizes().filter(s => (tea?.sizeIds || []).includes(s.id)); targetIds.forEach(id => { const el = document.getElementById(id); if (el) el.innerHTML = sizes.map(s=>`<option value="${h(s.id)}">${h(s.label)}</option>`).join(""); }); }
function adjustQty(id, delta) { const input = document.getElementById(id); if (input) input.value = Math.max(0, Number(input.value || 0) + Number(delta)); }
function updateGramCheck() { const box = document.getElementById("repackGramCheck"); if (!box) return; const fromQty = numberVal("repackFromQty"), toQty = numberVal("repackToQty"), fromGram = (sizeById(val("repackFromSize"))?.grams || 0) * fromQty, toGram = (sizeById(val("repackToSize"))?.grams || 0) * toQty, diff = toGram - fromGram; box.textContent = `กรัมต้นทางประมาณ ${fmt(fromGram)}g → ปลายทาง ${fmt(toGram)}g · ส่วนต่าง ${fmt(diff)}g`; box.className = Math.abs(diff) > fromGram * .08 ? "warning-box" : "success-box"; }
function writeDisabledAttr() { return (!state.online || state.busy) ? "disabled" : ""; }
function toast(message, type = "") { const root = document.getElementById("toastRoot"); const el = document.createElement("div"); el.className = `toast ${type}`; el.textContent = message; root.appendChild(el); setTimeout(() => el.remove(), 4200); }
function modal(title, bodyHtml, okText = "ตกลง") { return new Promise(resolve => { const root = document.getElementById("modalRoot"); root.innerHTML = `<div class="modal-backdrop"><div class="modal"><h3>${h(title)}</h3><div class="stack">${bodyHtml}</div><div class="modal-actions"><button class="ghost" id="modalCancel">ยกเลิก</button><button class="primary" id="modalOk">${h(okText)}</button></div></div></div>`; document.getElementById("modalCancel").onclick = () => { root.innerHTML = ""; resolve(false); }; document.getElementById("modalOk").onclick = () => { resolve(true); setTimeout(() => root.innerHTML = "", 0); }; }); }
function confirmDialog(title, message) { return modal(title, `<p>${h(message)}</p>`, "ยืนยัน"); }
function h(value) { return String(value ?? "").replace(/[&<>"']/g, c => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;", "'":"&#39;" }[c])); }
function val(id) { return document.getElementById(id)?.value || ""; } function numberVal(id) { return Number(document.getElementById(id)?.value || 0); } function onlyDigits(s) { return String(s || "").replace(/\D/g, ""); } function validPositiveInt(n) { return Number.isInteger(Number(n)) && Number(n) > 0; } function validNonNegativeInt(n) { return Number.isInteger(Number(n)) && Number(n) >= 0; }
function fmt(n) { return new Intl.NumberFormat("th-TH").format(Number(n || 0)); } function todayISO() { return new Date().toISOString().slice(0,10); } function dateStamp() { return new Date().toISOString().replace(/[:T]/g, "-").slice(0,19); }
function formatDate(date) { if (!date) return "-"; const d = new Date(String(date).length === 10 ? `${date}T00:00:00` : date); return isNaN(d) ? h(date) : d.toLocaleDateString("th-TH", { year:"numeric", month:"short", day:"numeric" }); }
function formatDateTime(date) { if (!date) return "-"; const d = date?.toDate ? date.toDate() : new Date(date); return isNaN(d) ? h(date) : d.toLocaleString("th-TH", { dateStyle:"short", timeStyle:"short" }); }
function stockDocId(branchId, teaId, sizeId) { return `${branchId}__${teaId}__${sizeId}`; } function makeId(prefix) { return `${prefix}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,9)}`; }
function makeSlugId(prefix, text) { const ascii = String(text).toLowerCase().normalize("NFKD").replace(/[^\w]+/g, "_").replace(/^_+|_+$/g, "").slice(0, 28); return `${prefix}_${ascii || Math.random().toString(36).slice(2,8)}_${Date.now().toString(36)}`; }
function nowOrServer() { return state.mode === "firebase" ? serverTimestamp() : new Date().toISOString(); } function chunk(arr, size) { const out = []; for (let i=0;i<arr.length;i+=size) out.push(arr.slice(i,i+size)); return out; }
function toCSV(rows) { return "\ufeff" + rows.map(row => row.map(cell => { const s = String(cell ?? ""); return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s; }).join(",")).join("\n"); }
function downloadFile(filename, content, mime) { const blob = new Blob([content], { type: mime }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = filename; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
function readFileAsDataURL(file) { return new Promise((resolve, reject) => { const r = new FileReader(); r.onload = () => resolve(r.result); r.onerror = reject; r.readAsDataURL(file); }); }
